server:
  port: 80

spring:
  datasource:
    url: "${spring.datasource.url}"
    username: "${spring.datasource.username}"
    password: "${spring.datasource.password}"
    driver-class-name: "${spring.datasource.driver-class-name}"
  data:
    mongodb:
      uri: "${spring.data.mongodb.uri}"
    redis:
      host: 127.0.0.1
      port: 6379
  jpa:
    open-in-view: false
    hibernate:
      ddl-auto: none
  sql:
    init:
      mode: always
  output:
    ansi:
      enabled: always
  security:
    oauth2:
      client:
        registration:
          kakao:
            client-id: "${kakao.client-id}"
            client-secret: "${kakao.secret}"
            client-authentication-method: client_secret_post
            redirect-uri: "${kakao.redirect-uri}"
            authorization-grant-type: "${kakao.authorization-grant-type}"
            client-name: kakao
            scope: "${kakao.scope}"
        provider:
          kakao:
            token-uri: "${kakao.token-uri}"
            user-info-uri: "${kakao.user-info-uri}"
            user-name-attribute: "${kakao.attribute}"
            authorization-uri: "${kakao.authorization-uri}"
  mvc:
    pathmatch:
      matching-strategy: PATH_PATTERN_PARSER

management:
  endpoints:
    web:
      exposure:
        include: "health"
  endpoint:
    health:
      show-details: never
  health:
    redis:
      enabled: true
    db:
      enabled: true
  prometheus:
    metrics:
      export:
        enabled: true

secret:
  key: "${secret.key}"