server:
  port: 80

spring:
  datasource:
    url: "${spring_datasource_url}"
    username: "${spring_datasource_username}"
    password: "${spring_datasource_password}"
    driver-class-name: "${spring_datasource_driver_class_name}"
  data:
    mongodb:
      uri: "${spring_data_mongodb_uri}"
  jpa:
    open-in-view: false
    hibernate:
      ddl-auto: none
  sql:
    init:
      mode: always
  output:
    ansi:
      enabled: always
  security:
    oauth2:
      client:
        registration:
          kakao:
            client-id: "${kakao_client_id}"
            redirect-uri: "${kakao_redirect_uri}"
            authorization-grant-type: "${kakao_authorization_grant_type}"
        provider:
          kakao:
            token-uri: "${kakao_token_uri}"
            user-info-uri: "${kakao_user_info_uri}"

  mvc:
    pathmatch:
      matching-strategy: PATH_PATTERN_PARSER