server:
  port: 80

spring:
  datasource:
    url: "${spring.datasource.url}"
    username: "${spring.datasource.username}"
    password: "${spring.datasource.password}"
    driver-class-name: "${spring.datasource.driver-class-name}"
  data:
    mongodb:
      uri: "${spring.data.mongodb.uri}"
    redis:
      host: "${spring.data.redis.host}"
      port: "${spring.data.redis.port}"
  jpa:
    open-in-view: false
    hibernate:
      ddl-auto: none
  sql:
    init:
      mode: always
  output:
    ansi:
      enabled: always
  security:
    oauth2:
      client:
        registration:
          kakao:
            client-id: "${kakao.client-id}"
            redirect-uri: "${kakao.redirect-uri}"
            authorization-grant-type: "${kakao.authorization-grant-type}"
        provider:
          kakao:
            token-uri: "${kakao.token-uri}"
            user-info-uri: "${kakao.user-info-uri}"
  mvc:
    pathmatch:
      matching-strategy: "${mvc.matching-strategy}"