server:
  port: 80

spring:
  datasource:
    url: "${spring_datasource_url}"
    username: "${spring_datasource_username}"
    password: "${spring_datasource_password}"
    driver-class-name: "${spring_datasource_driver_class_name}"
  data:
    mongodb:
      uri: "${spring_data_mongodb_uri}"
    redis:
      host: "${spring_data_redis_uri}"
      port: 6379
  jpa:
    open-in-view: false
    hibernate:
      ddl-auto: none
  sql:
    init:
      mode: always
  output:
    ansi:
      enabled: always
  security:
    oauth2:
      client:
        registration:
          kakao:
            client-id: "${kakao_client_id}"
            client-secret: "${kakao_secret}"
            client-authentication-method: client_secret_post
            redirect-uri: "${kakao_redirect_uri}"
            authorization-grant-type: "${kakao_authorization_grant_type}"
            client-name: kakao
            scope: "${kakao_scope}"
        provider:
          kakao:
            token-uri: "${kakao_token_uri}"
            user-info-uri: "${kakao_user_info_uri}"
            user-name-attribute: "${kakao_attribute}"
            authorization-uri: "${kakao_authorization_uri}"
  mvc:
    pathmatch:
      matching-strategy: PATH_PATTERN_PARSER

management:
  endpoints:
    web:
      exposure:
        include: "health"
  endpoint:
    health:
      show-details: never
  health:
    redis:
      enabled: true
    db:
      enabled: true
  prometheus:
    metrics:
      export:
        enabled: true